spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: 192.168.75.1
      port: 26379
      password: 123456
server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl